[package]
name = "smash-lvd"
version = "0.1.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "lvd"
path = "src/lib.rs"

[dependencies]
binrw = { git = "https://github.com/jam1garner/binrw" }
binwrite = "0.2.1"
